version: "3"
services:
  train:
    image: vishwakarkalle/phonepaytrain:v1
    ports:
      - "8000:80"
    volumes:
      - "trainvol"

  movie:
    image: vishwakarkalle/phonepaymovie:v1
    ports:
      - "8001:80"
    volumes:
      - "movievol"

  metro:
    image: vishwakarkalle/phonepaymetro:v1
    ports:
      - "8003:80"
    volumes:
      - "metrovol"
